### ISSUE TITLE
Alerting in sensu with SSL rabbitmq

### ISSUE THREAD

**Issue by jothoma1** [cvtienhoven/graylog-plugin-sensu#3]
Hi, i'm using sensu with SSL in rabbitmq. 
When using the sensu alerting it gives me an error about ssl (my certificates are ok) : 

> 2017-06-26T13:39:39.923+02:00 ERROR [ForgivingExceptionHandler] An unexpected connection driver error occured
java.net.SocketException: Socket is closed
        at sun.security.ssl.SSLSocketImpl.checkEOF(SSLSocketImpl.java:1532) ~[?:1.8.0_91]
        at sun.security.ssl.AppInputStream.read(AppInputStream.java:95) ~[?:1.8.0_91]
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:246) ~[?:1.8.0_91]
        at java.io.BufferedInputStream.read(BufferedInputStream.java:265) ~[?:1.8.0_91]
        at java.io.DataInputStream.readUnsignedByte(DataInputStream.java:288) ~[?:1.8.0_91]
        at com.rabbitmq.client.impl.Frame.readFrom(Frame.java:91) ~[graylog.jar:?]
        at com.rabbitmq.client.impl.SocketFrameHandler.readFrame(SocketFrameHandler.java:164) ~[graylog.jar:?]
        at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:571) [graylog.jar:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
2017-06-26T13:39:39.923+02:00 WARN  [AlertNotificationsSender] Alarm callback <Sensu Alarm Callback> failed. Skipping.
org.graylog2.plugin.alarms.callbacks.AlarmCallbackException: null
        at org.graylog.SensuAlarmCallback.call(SensuAlarmCallback.java:113) ~[?:?]
        at org.graylog2.alerts.AlertNotificationsSender.send(AlertNotificationsSender.java:58) ~[graylog.jar:?]
        at org.graylog2.alerts.AlertScanner.handleRepeatedAlert(AlertScanner.java:51) ~[graylog.jar:?]
        at org.graylog2.alerts.AlertScanner.checkAlertCondition(AlertScanner.java:77) ~[graylog.jar:?]
        at org.graylog2.periodical.AlertScannerThread.lambda$doRun$0(AlertScannerThread.java:72) ~[graylog.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1249) [?:1.8.0_91]
        at org.graylog2.periodical.AlertScannerThread.doRun(AlertScannerThread.java:72) [graylog.jar:?]
        at org.graylog2.plugin.periodical.Periodical.run(Periodical.java:77) [graylog.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_91]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_91]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_91]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_91]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_91]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]

If you have an idea ?

**Comment by cvtienhoven** [comment]
What does the logging of RabbitMQ say when connecting?

**Comment by jothoma1** [comment]
Ok found it :) it was a simple error, if i put _rabbitmq_virtual_host: /sensu_ it doesn't work so i try with :
_rabbitmq_virtual_host: sensu_ and it works like a charm !

And the test button of the notifications in Graylog works too ! so you can close my other issue...
Sorry for this, everything works as expected now !
Thanks a lot
